### ISSUE TITLE
Preprocessing settings for raw->resync

### ISSUE THREAD

**Issue by he-so** [marc-invalid/chipwhisperer-marc#1]
Hi,

thanks a lot for providing so much code and examples! I try to reproduce the results you had with this fork. Currently, I have no luck generating the traces you provide in HCS301_sync.zip from preprocessing the traces in HCS301_raw.zip. What were the preprocessing modules and exact settings involved in generating them?
What I did: slice-to-slot preprocessing, slice width 400 samples, fine-tune: Peak(max). With these settings the trace explorer does not show the rainbow spikes and teh attack module does not reveal the key.

Regards,
Henning

**Comment by marc-invalid** [comment]
Thanks for looking into this project and sorry for the late reply.  I didn't check my account for a long time.

Unfortunately I don't remember the exact settings.  Also, don't have access to the system at this moment.  I might be able to check back on it in several weeks, though.

I have just tried to reproduce the settings off head.  They are not *exactly* what was used (I won't be able to look those up until in several weeks time), but the results look roughly similar.

Preprocessor Module #0:  Resync Peak Detect

  - Settings (that are different from defaults):

      * Peak Type:   Max
      * Point range: 100, 250
      * Valid limit: 0.25

      * Enabled:     Yes

  - The point range was chosen after enabling ALL traces in the output plot,
    although the plot was very slow to generate and sluggish.  To show all
    traces, do the following:

      * Left hand side: select 'Results' tab
      * Scroll down to 'Trace Output Plot'
      * Trace range = 0, 500
      * Click 'Redraw'

  - Valid limit was chosen because it does not select the many lower peaks of
    each round.

  - The output looks perfectly good on the left side (where the peak detection
    takes place).  On the right side it looks very bad, because of the RC
    oscillator in the HCS301 drifting away.

Preprocessor Module #1:  Slice-to-Slot

  - Settings (that are different from defaults):

      * Ref slice window:  130, 330
      * Slice width (Pts): 200

      * Enabled:           Yes

  - Ref slice windows was chosen by looking at the output of the previous module,
    starting shortly before the highest rising peak (and until the next such peak).
    This peak seems to be the beginning of each round in the HCS301, but you can
    also try different alignments.

  - Slice width was chosen to make the output look continuous (like the input),
    although this is not actually correct.  There is a seam between each round,
    a few samples might be missing or duplicated at this point.

  - The output now looks equally good in all places, from left to right.  The
    oscillator drift has disappeared!
